version: 2
updates:
  # Gestão de dependências (exemplo com NPM)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Asuncion"
    open-pull-requests-limit: 10
    
    # Agrupamento correto para evitar poluição no histórico de Commits
    groups:
      dependencies:
        applies-to: version-updates
        patterns:
          - "*"

    labels:
      - "security"
      - "automation"

  # Monitoramento de GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
